name: Park_Elite
description: "Estacionamiento automatizado"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  json_serializable: ^6.9.4
  flutter_secure_storage: ^9.2.4
  lucide_icons: ^0.257.0
  google_fonts: ^6.2.1
  connectivity_plus: ^6.1.4
  internet_connection_checker: ^1.0.0+1
  device_info_plus: ^11.5.0
  flutter_local_notifications: ^18.0.1
  workmanager: ^0.9.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo_entero_premium.png"
  adaptive_icon:
    foreground: "assets/images/app_icon_logo.png"
    background: "assets/images/fondo_logo_premium.png"

flutter:
  uses-material-design: true
  assets:
    - "assets/images/2.png"
    - "assets/images/app_icon_logo.png"
    - "assets/images/app_icon_background.png"
    - "assets/images/fondo_logo_premium.png"
    - "assets/images/logo_entero_premium.png"
  fonts:
    - family: SanFrancisco
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf